### PR TITLE
Added zoom in functionality to the battle grid  

### PR DESCRIPTION
**Pull request by rganesh1234567**
I added zoom in functionality to the battle grid. Also updated the css folder to make zoom in smoother. Added + and - buttons to the main html file. 

For some reason I don't see the battle grid when i run it on my browser. I could see it last time before the object token files were merged into main. Can you check and see what could be causing the error?

### CODE REVIEW

**Comment by emily-shaw** [comment]
I see the battle gird, you need to hit create grid to see it, also object is on a seperate grid called objectGrid, so remember to add whatever you did to the battle grid to object grid. Also you need to keep position: absolute in #battle-grid, #object-grid in css so object grid can have z index of 1

**Comment by emily-shaw** [comment]
Im gonna let you make the cahnge because im not sure how many change you made to the battlegrid, but just remember to apply them all to obejct grid and add back the position: absolute(NOT relative!!!)

**Comment by emily-shaw** [comment]
still doesn't seem to work for me, did you add all your change to battlegrid in grid.js to objectgrid?

**Comment by rganesh1234567** [comment]
can you atleast see the battle grid when you click create grid. In my browser, nothing happens when i click create grid (even before i made any changes) .

**Comment by TedDPig123** [comment]
i can see the grid after clicking create grid

**Comment by emily-shaw** [comment]
I can see create grid too

**Comment by rganesh1234567** [comment]
I edited grid.js to allow for both the grids. Does it work on your side now? I think there is some issue with my browser, because if you look at this previous branch https://github.com/TedDPig123/326_Project/tree/feature/rudy-zooming, the zoom in function works perfectly, and i can see the grid too.

**Review by emily-shaw — COMMENTED** [review]
looks good, only problem is the zoom in and out seems to be a little delay in showing when switch between object and battle grid, other then that all seems good

**Pull request merged**
